import { ReactNode } from 'react';
import './globals.css';

export const metadata = {
  title: 'Eliane Perrut ♡ Sweet Cake',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
